#Ekstraksi Data

Akan diekstraksi data dari 100 halaman review pada FemaleDaily sebagai batasan agar proses ekstraksi tidak dilakukan terlalu lama. Beirkut adalah syntax yang digunakan untuk mendapatkan data

In [66]:
import pandas as pd
from time import sleep
from random import randint
import numpy as np
from bs4 import BeautifulSoup
import requests

#Pembuatan array untuk menyimpan data yang diekstraksi
id = []
nama = []
umur = []
id_produk = []
produk = []
brand = []
nilai = []
pembelian = []
kepuasan = []
rekomendasi = []
jenis = []
date = []
tempat = []
tipe =[]
parent = []
waktu_pemakaian = []
penggunaan = []
jumlah_review = []
review = []

url='https://reviews.femaledaily.com/?page='

for page in range(1,100):
    result = requests.get(url)
    temp = result.content
    soup = BeautifulSoup(result.content, 'html.parser')
    string_html = str(result.content)
    print(page)

    startr = '"storeNewestReviews":'
    starting_splitr = string_html.split(startr,1)[1]
    end_splitr = starting_splitr.split('storeProductsCampaign',1)[0]
    raw_list_review = ['"text":"'+itemr for itemr in end_splitr.split('"text":"')[1:]]
    for itemr in raw_list_review:
        start_tokenr = '"text":"'
        end_tokenr = ',"is_like"'
        temp  = itemr.split(start_tokenr, 1)[1]
        resultr = temp.split(end_tokenr, 1)[0]
        review.append(resultr)
    review = list(set(review))

    #Ekstraksi kategori produk
    start = '"storeNewestReviews":'
    starting_split = string_html.split(start,1)[1]
    end_split = starting_split.split('"storeProducts"',1)[0]
    raw_list_jenis = ['"category":{"name":"'+item for item in end_split.split('"category":{"name":"')[1:]]
    for item in raw_list_jenis:
        start_token = '"category":{"name":"'
        end_token = '","slug"'
        temp  = item.split(start_token, 1)[1]
        hasil = temp.split(end_token, 1)[0]
        jenis.append(hasil)

    #Ekstraksi tanggal dibuatnya review
    yuhu = '"storeNewestReviews":'
    starting = string_html.split(yuhu,1)[1]
    end_splits = starting.split('"storeProducts"',1)[0]
    raw_list_date = ['"date":"'+yo for yo in end_splits.split('"date":"')[1:]]
    for yo in raw_list_date:
        start_letsgo = '"date":"'
        end_letsgo = '","text":'
        temp  = yo.split(start_letsgo, 1)[1]
        hisal = temp.split(end_letsgo, 1)[0]
        date.append(hisal)

    # Ekstraksi data tempat pembelian produk
    yuhu1 = '"storeNewestReviews":'
    starting1 = string_html.split(yuhu1,1)[1]
    end1_splits = starting1.split('"storeProducts"',1)[0]
    raw_list_tempat = ['"place_to_get":{"place":"'+wi for wi in end1_splits.split('"place_to_get":{"place":"')[1:]]
    for wi in raw_list_tempat:
        start1_letsgo = '"place_to_get":{"place":"'
        end1_letsgo = '","order"'
        temp  = wi.split(start1_letsgo, 1)[1]
        hisal1 = temp.split(end1_letsgo, 1)[0]
        tempat.append(hisal1)

    #Ekstraksi data kategori parent dari produk yang diulas
    yuhu2 = '"storeNewestReviews":'
    starting2 = string_html.split(yuhu2,1)[1]
    end2_splits = starting2.split('"storeProducts"',1)[0]
    raw_list_parent = ['"parent":{"name":"'+wo for wo in end2_splits.split('"parent":{"name":"')[1:]]
    for wo in raw_list_parent:
        start11_letsgo = '"parent":{"name":"'
        end11_letsgo = '","slug"'
        temp  = wo.split(start11_letsgo, 1)[1]
        hisal11 = temp.split(end11_letsgo, 1)[0]
        parent.append(hisal11)

    #Ekstraksi id user
    yuhu21 = '"storeNewestReviews":'
    starting21 = string_html.split(yuhu21,1)[1]
    end21_splits = starting21.split('"storeProducts"',1)[0]
    raw_list_id = ['"user":{"id":'+wo1 for wo1 in end21_splits.split('"user":{"id":')[1:]]
    for wo1 in raw_list_id:
        start111_letsgo = '"user":{"id":'
        end111_letsgo = ',"username"'
        temp  = wo1.split(start111_letsgo, 1)[1]
        hisal111 = temp.split(end111_letsgo, 1)[0]
        id.append(hisal111)       

    # Ekstraksi id produk yang diulas
    mulai = '"storeNewestReviews":'
    starting211 = string_html.split(mulai,1)[1]
    end211_splits = starting211.split('"storeProducts"',1)[0]
    raw_list_id = ['"product":{"id":'+wo11 for wo11 in end211_splits.split('"product":{"id":')[1:]]
    for wo11 in raw_list_id:
        start1111_letsgo = '"product":{"id":'
        end1111_letsgo = ',"image"'
        temp  = wo11.split(start1111_letsgo, 1)[1]
        hisal1111 = temp.split(end1111_letsgo, 1)[0]
        id_produk.append(hisal1111)

    #Ekstraksi data waktu pemakaian produk
    mulai1 = '"storeNewestReviews":'
    start_line = string_html.split(mulai1,1)[1]
    end_line = start_line.split('"storeProducts"',1)[0]
    raw_list_waktu = ['"duration_of_use":"'+nilai2 for nilai2 in end_line.split('"duration_of_use":"')[1:]]
    for nilai2 in raw_list_waktu:
        start_now = '"duration_of_use":"'
        end_now = '","place_to_get"'
        temp  = nilai2.split(start_now, 1)[1]
        hasilnya = temp.split(end_now, 1)[0]
        waktu_pemakaian.append(hasilnya)

    #Ekstraksi data mulai penggunaan
    mulai11 = '"storeNewestReviews":'
    start_line1 = string_html.split(mulai11,1)[1]
    end_line1 = start_line1.split('"storeProducts"',1)[0]
    raw_list_peng = ['"is_firsttime_use":"'+nilai1 for nilai1 in end_line1.split('"is_firsttime_use":"')[1:]]
    for nilai1 in raw_list_peng:
        start_now1 = '"is_firsttime_use":"'
        end_now1 = '","duration_of_use"'
        temp  = nilai1.split(start_now1, 1)[1]
        hasilnya = temp.split(end_now1, 1)[0]
        penggunaan.append(hasilnya)
      
    #Ekstraksi data-data yang dapat diambil langsung menggunakan struktur html nya
    project = soup.find_all("div", class_="review-card")

    for value in project:
        #Ekstraksi nama pengguna
        name = value.find_all("p", class_="profile-username")
        nama.append(name)

        #Ekstraksi rentang umur pengguna
        age = value.find_all("p", class_="profile-age")
        umur.append(age)

        #Ekstraksi nama produk yang diulas
        product = value.find_all("p", class_="product-name")
        produk.append(product)

        #Ekstraksi brand produk yang diulas
        merek = value.find_all("h3", class_="product-brand")
        brand.append(merek)

        #Ekstraksi nilai rating produk secara total
        puas = value.find_all('span', class_='rating-text')
        nilai.append(puas)

        #Ekstraksi data apakah pengguna merekomendasikan produk atau tidak
        recommend = value.find_all('p', class_='recommend') 
        rekomendasi.append(recommend)
        
        #Ekstraksi tipe kulit pengguna
        tipes = value.find_all('p', class_='profile-description')
        tipe.append(tipes)

        #Ekstraksi jumlah review terhadap produk yang sedang diulas
        jumlach = value.find_all('span', class_='rating-total')
        jumlah_review.append(jumlach)

        #Ekstraksi besar rating yang diberikan pengguna kepada produk yang diulas
        full = len(value.find_all(('i'), class_ = "icon-ic_big_star_full"))
        kepuasan.append(full)
        
    url = 'https://reviews.femaledaily.com/?page='+ str(page+1)

#Pembuatan dataframe dari data yang diekstrak   
a = {'date':date,'id' : id, 'nama' : nama ,'umur' : umur , 'id_produk':id_produk, 
     'produk': produk , 'brand':brand , 'nilai_produk':nilai ,'jumlah_review':jumlah_review, 
     'tempat_beli':tempat, 'jenis': jenis,'kategori': parent, 'tipe_kulit':tipe,
     'waktu_pemakaian':waktu_pemakaian, 'penggunaan':penggunaan, 'kepuasan': kepuasan,
     'rekomendasi': rekomendasi, 'review': review}

skincare = pd.DataFrame.from_dict(a, orient='index')
skincare = skincare.transpose()

skincare.head(5)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

                       date  ...                                             review
0  2022-01-18T07:50:29.000Z  ...  OMOOO gak ngerti ini bener2 ngelembabin dan se...
1  2022-01-18T07:44:47.000Z  ...  Wanginya kaya YSL Black opium. Tapi beli ini k...
2  2022-01-18T07:44:07.000Z  ...  Kalau ini parfum biasanya dipakai kalau pulang...
3  2022-01-18T07:43:56.000Z  ...  Pertama kalinya nih nyobain whitening lifting ...
4  2022-01-18T07:41:35.000Z  ...  sebenarnya serum ini kandungannya bagus ada vi...

[5 rows x 18 columns]

In [67]:
skincare.shape

(990, 18)

Selanjutnya, data akan disimpan dalam bentuk CSV agar dapat dibersihkan bentuk html-nya

In [68]:
from google.colab import files
skincare.to_csv('data_ekstraksi.csv', header = True) 
#files.download("data_tubes.csv")

# Data Cleaning

In [92]:
data = pd.read_csv('/content/data_ekstraksi.csv')
data.head(2)

   Unnamed: 0  ...                                             review
0           0  ...  OMOOO gak ngerti ini bener2 ngelembabin dan se...
1           1  ...  Wanginya kaya YSL Black opium. Tapi beli ini k...

[2 rows x 19 columns]

Data di-upload kembali. Kemudian, data baru dikeluarkan dan dilihat bentuknya. Dpaat diihat bahwa bentuk dari data sebelum diganti menjadi CSV dengan data baru memiliki format yang berbeda. Data yang lama memiliki "[[ ]]" yang merupakan penyingkatan dari bentuk html. Setelah data diganti menjadi csv, data html tersebut terlihat sehingga harus dibersihkan terlebih dahulu

Data akan dibersihkan dari bentuk html-nya dengan syntax berikut ini

In [93]:
#Pembersihan data dari bentuk html-nya
from bs4 import BeautifulSoup

date = []
nama = []
umur = []
produk = []
brand = []
nilai_produk = []
tempat_beli = []
jenis = []
kategori = []
tipe_kulit = []
kepuasan = []
rekomendasi = []
jumlah_review = []

for text in data['nama']:
  soup = BeautifulSoup(text,"html.parser")
  name = soup.find('a').get_text()
  nama.append(name)
data.loc[:, 'nama'] = nama

for text in data['umur']:
  soup = BeautifulSoup(text,"html.parser")
  p = soup.find('p')
  if p is not None:
    age = p.get_text()
    umur.append(age)
data['umur']= pd.DataFrame(umur)

for text in data['produk']:
  soup = BeautifulSoup(text,"html.parser")
  produk1 = soup.find('a').get_text()
  produk.append(produk1)
data.loc[:, 'produk'] = produk

for text in data['brand']:
  soup = BeautifulSoup(text,"html.parser")
  merk = soup.find('a').get_text()
  brand.append(merk)
data.loc[:, 'brand'] = brand

for text in data['nilai_produk']:
  soup = BeautifulSoup(text,"html.parser")
  mantap = soup.find('span')
  if mantap is not None:
    lala = mantap.get_text()
    nilai_produk.append(lala)
data['nilai_produk']= pd.DataFrame(nilai_produk)

for text in data['tipe_kulit']:
  soup = BeautifulSoup(text,"html.parser")
  kulit = soup.find('p')
  if kulit is not None:
    lala1 = kulit.get_text()
    tipe_kulit.append(lala1)
data['tipe_kulit']= pd.DataFrame(tipe_kulit)

for text in data['rekomendasi']:
  soup = BeautifulSoup(text,"html.parser")
  mantap4 = soup.find('p')
  if mantap4 is not None:
    lala4 = mantap4.get_text()
    rekomendasi.append(lala4)
data['rekomendasi']= pd.DataFrame(rekomendasi)

for text in data['jumlah_review']:
  soup = BeautifulSoup(text,"html.parser")
  mantap3 = soup.find('span')
  if mantap3 is not None:
    lala3 = mantap3.get_text()
    jumlah_review.append(lala3)
data['jumlah_review']= pd.DataFrame(jumlah_review)

data.head(5)

   Unnamed: 0  ...                                             review
0           0  ...  OMOOO gak ngerti ini bener2 ngelembabin dan se...
1           1  ...  Wanginya kaya YSL Black opium. Tapi beli ini k...
2           2  ...  Kalau ini parfum biasanya dipakai kalau pulang...
3           3  ...  Pertama kalinya nih nyobain whitening lifting ...
4           4  ...  sebenarnya serum ini kandungannya bagus ada vi...

[5 rows x 19 columns]

Dapat dilihat bahwa data bentuk HTML sudah dibersihkan dan diambil data intinya saja. Kemudian, akan kolom tipe kulit akan dipisah menjadi tiga kolom, yaitu kolom tipe kulit, warna kulit, dan tone kulit

In [94]:
#Slicing kolom tipe_kulit
data[['tipe_kulit', 'warna_kulit', 'tone_kulit']] = data['tipe_kulit'].str.split(', ', 2, expand=True)
data.head()

   Unnamed: 0                      date  ...   warna_kulit tone_kulit
0           0  2022-01-18T07:50:29.000Z  ...        Medium    Neutral
1           1  2022-01-18T07:44:47.000Z  ...        Medium       Warm
2           2  2022-01-18T07:44:07.000Z  ...  Medium Light    Neutral
3           3  2022-01-18T07:43:56.000Z  ...  Medium Light    Neutral
4           4  2022-01-18T07:41:35.000Z  ...        Medium    Neutral

[5 rows x 21 columns]

In [95]:
data.shape

(990, 21)

Lalu, data akan dideteksi jumlah nilai Nullnya

In [96]:
# Melihat data hilang
data.isna().sum()

Unnamed: 0          0
date                0
id                  0
nama                0
umur                5
id_produk           0
produk              0
brand               0
nilai_produk       55
jumlah_review      55
tempat_beli         0
jenis               0
kategori            0
tipe_kulit          0
waktu_pemakaian     0
penggunaan          0
kepuasan            0
rekomendasi         4
review             10
warna_kulit        67
tone_kulit         67
dtype: int64

Data null dibuang

In [97]:
#Membuang data hilang
data = data.dropna()

Kemudian, terdapat beberapa data emoji yang terekstrasi dalam bentuk unicode. Dengan ini, akan dihilangkan teks emoji yang terdapat pada review.

In [98]:
#Pembersihan emoji
import re
df = data
df['review'] = data['review'].str.replace(r'\\\w+', '')
df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

   Unnamed: 0                      date  ...   warna_kulit tone_kulit
0           0  2022-01-18T07:50:29.000Z  ...        Medium    Neutral
1           1  2022-01-18T07:44:47.000Z  ...        Medium       Warm
2           2  2022-01-18T07:44:07.000Z  ...  Medium Light    Neutral
3           3  2022-01-18T07:43:56.000Z  ...  Medium Light    Neutral
4           4  2022-01-18T07:41:35.000Z  ...        Medium    Neutral

[5 rows x 21 columns]

Dilakukan transformasi bentuk data pada kolom rekomendasi dari bentuk string menjadi bentuk numerik biner

In [99]:
#Pengubahan kolom rekomendasi : 1 untuk merekomendasikan produk, 0 untuk tidak merekomendasikan produk
data['rekomendasi'] = data['rekomendasi'].str.replace(r"\b(?!doesn'|t\b)\w+.",'')
data["rekomendasi"] = [0 if ele  == "doesn't  " else 1 for ele in data["rekomendasi"]]

Dilakkan transformasi bentuk data pada kolom penggunaan menjadi biner

In [100]:
#Pengubahan kolom rekomendasi : 1 untuk penggunaan pertama kali, 0 untuk bukan penggunaan pertama kali
data["penggunaan"] = ["0" if ele  == "n" else "1" for ele in data["penggunaan"]]
data.head(5)

   Unnamed: 0                      date  ...   warna_kulit tone_kulit
0           0  2022-01-18T07:50:29.000Z  ...        Medium    Neutral
1           1  2022-01-18T07:44:47.000Z  ...        Medium       Warm
2           2  2022-01-18T07:44:07.000Z  ...  Medium Light    Neutral
3           3  2022-01-18T07:43:56.000Z  ...  Medium Light    Neutral
4           4  2022-01-18T07:41:35.000Z  ...        Medium    Neutral

[5 rows x 21 columns]

Dilakukan penghapusan simbol '( )' pada kolom jumlah review agar si kolom hanya berbentuk numerik

In [101]:
#Penghapusan string ()
data['jumlah_review'] = data['jumlah_review'].str.replace(r'\(', '')
data['jumlah_review'] = data['jumlah_review'].str.replace(r'\)','')
data.head()

   Unnamed: 0                      date  ...   warna_kulit tone_kulit
0           0  2022-01-18T07:50:29.000Z  ...        Medium    Neutral
1           1  2022-01-18T07:44:47.000Z  ...        Medium       Warm
2           2  2022-01-18T07:44:07.000Z  ...  Medium Light    Neutral
3           3  2022-01-18T07:43:56.000Z  ...  Medium Light    Neutral
4           4  2022-01-18T07:41:35.000Z  ...        Medium    Neutral

[5 rows x 21 columns]

In [102]:
#Pengubahan tipe data kolom
data['penggunaan'] = data['penggunaan'].astype('int')
data['jumlah_review'] = data['jumlah_review'].astype('int')
data.dtypes

Unnamed: 0          int64
date               object
id                  int64
nama               object
umur               object
id_produk           int64
produk             object
brand              object
nilai_produk       object
jumlah_review       int64
tempat_beli        object
jenis              object
kategori           object
tipe_kulit         object
waktu_pemakaian    object
penggunaan          int64
kepuasan            int64
rekomendasi         int64
review             object
warna_kulit        object
tone_kulit         object
dtype: object

Kemudian, akan dihapus kolom pertama yang tidak akan relevan untuk digunakan pada pengolahan data berjenis apa pun

In [104]:
data = data.drop(['Unnamed: 0'], axis = 1)
data.head()

                       date      id  ...   warna_kulit tone_kulit
0  2022-01-18T07:50:29.000Z  428578  ...        Medium    Neutral
1  2022-01-18T07:44:47.000Z  917588  ...        Medium       Warm
2  2022-01-18T07:44:07.000Z  900967  ...  Medium Light    Neutral
3  2022-01-18T07:43:56.000Z  594881  ...  Medium Light    Neutral
4  2022-01-18T07:41:35.000Z  992291  ...        Medium    Neutral

[5 rows x 20 columns]

Data sudah dibersihkan dan siap untuk digunakan